# Generated by Django 3.2.4 on 2021-08-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('Trainer', models.CharField(max_length=12)),
                ('course_code', models.CharField(max_length=12)),
                ('syllabus', models.FileField(null=True, upload_to='documents/%y/%m/%d')),
                ('Description', models.TextField()),
            ],
        ),
    ]
