# Generated by Django 3.2.4 on 2021-08-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveBigIntegerField()),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('student_id', models.CharField(max_length=15)),
                ('student_image', models.ImageField(upload_to='')),
                ('city', models.CharField(max_length=10)),
                ('medical_report', models.FileField(upload_to='')),
                ('admission_date', models.CharField(max_length=15)),
                ('class_name', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=14)),
                ('guardian_phonenumber', models.CharField(max_length=15)),
                ('guardian_name', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=20)),
                ('academic_year', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=6)),
                ('languages', models.CharField(choices=[('E', 'English'), ('k', 'Kiswahili'), ('F', 'French')], max_length=15)),
                ('nationality', models.CharField(choices=[('k', 'Kenya'), ('u', 'Ugandan'), ('R', 'Rwandese'), ('S', 'sudanese'), ('S', 'SouthSudanese')], max_length=15)),
            ],
        ),
    ]
